/* This file is automatically generated by the DailyBuild script. */
#if 0
// just a dummy section to make the file more like the generated one from the build maching
// note:  if the format of this file changes dramatically, you will have to change 
// CSharpVersionWriter in BuildTools, as we use it to generate src\include\dotNet\AssemblyVersion.cs
// for C# projects
#else // MAX
  #define VERSION_STRING  "Imoogi with PDBs I966_RL_x64 02-27-2017 18:16 fb5f947b6db9af81810694b0f4bdcb52386a6b14"
  #define VERSION_INT   966
#endif

