/////////////////////////////////////////////////////////////
// cxr_test.h
//
// This file was generated by CXR, the literal string encryptor.
// CXR, Copyright 2002, Smaller Animals Software, Inc., all rights reserved.
//
// Please do not edit this file. Any changes here will be overwritten on the next compile.
// If you wish to make changes to a string, please edit:
//     test.cxr
//

/////////////////////////////////////////////////////////////

#pragma once
#include "cxr_inc.h"

// cxr 적용 테스트입니당

///////////////////////////
#ifdef _USING_CXR
#define STR_CXRTEST1 	_CXR("\x8d\x83\x8e\x83\x87\x82\x87\x86\x83\x86\x86\x8f\x88\x89\x81\x88\x8a\x81\x8f\x8f\x8b\x88\x8c\x86\x8e\x87\x86\x8d\x87\x85\x84\x8c\x88\x80\x87\x8c\x8d\x8c\x8d\x84\x84\x8d\x8d\x8b\x8a\x80\x8c\x8f\x8e\x85\x8f\x89\x89\x80\x8f\x87\x83\x8c\x89\x82\x85\x86\x80\x85\x87\x87")
#else
#define STR_CXRTEST1 _CXR("Your all bases are belong to us.")
#endif

///////////////////////////
#ifdef _USING_CXR
#define STR_CXRTEST2 	_CXR("\x87\x86\x81\x8f\x8b\x8d\x8c\x88\x80\x8e\x80\x82\x87\x84\x84\x85\x86\x8c\x84\x8d")// 디파인 뒤에 주석이 달린 경우를 테스트
#else
#define STR_CXRTEST2 _CXR("It's You!")// 디파인 뒤에 주석이 달린 경우를 테스트
#endif

///////////////////////////
#ifdef _USING_CXR
#define STR_CXRTEST3 	_CXR("\x88\x8c\x85\x8b\x84\x8a\x86\x8d\x81\x8b")		// 디파인 뒤에 공백을 두고 주석이 달린 경우를 테스트
#else
#define STR_CXRTEST3 _CXR("Aye.")		// 디파인 뒤에 공백을 두고 주석이 달린 경우를 테스트
#endif


